const DATA=window.VISIT_DATA||[];
const SCENES=[{"id": "smalltalk", "title": "见面与寒暄"}, {"id": "opening", "title": "会议开场与人员介绍"}, {"id": "company", "title": "DA Controls 公司介绍"}, {"id": "discovery", "title": "客户产品与供应链了解"}, {"id": "technical", "title": "技术要求澄清"}, {"id": "price", "title": "价格与成本讨论"}, {"id": "sample", "title": "图纸、样品、测试与 NDA"}, {"id": "factory", "title": "工厂与实验室参观"}, {"id": "closing", "title": "会议收口与下一步"}, {"id": "social", "title": "用餐与非正式交流"}];
let mode='learn',scene=SCENES[0].id,memIdx=0,reviewIdx=0,answerVisible=false,memFilter='all';
const states=JSON.parse(localStorage.getItem('alan_visit_english_states_v1')||'{}');
let voices=[];function loadVoices(){voices=speechSynthesis?.getVoices?.()||[]}if('speechSynthesis'in window){loadVoices();speechSynthesis.onvoiceschanged=loadVoices}
function speak(t){if(!('speechSynthesis'in window))return alert('当前浏览器不支持语音朗读');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.88;u.voice=voices.find(v=>/en-US/i.test(v.lang)&&/Samantha|Ava|Allison|Susan|Alex|Joelle|Nicky/i.test(v.name))||voices.find(v=>/en-US/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))||null;speechSynthesis.speak(u)}
function save(){localStorage.setItem('alan_visit_english_states_v1',JSON.stringify(states))}function label(s){return s==='know'?'熟练':s==='fuzzy'?'模糊':s==='no'?'不熟':'未学习'}
function updateStats(){let know=0,fuzzy=0,no=0,marked=0;DATA.forEach(x=>{const s=states[x.id];if(s){marked++;if(s==='know')know++;if(s==='fuzzy')fuzzy++;if(s==='no')no++}});stTotal.textContent=DATA.length;stKnow.textContent=know;stFuzzy.textContent=fuzzy;stNo.textContent=no;pstate.textContent=`${marked} / ${DATA.length} 已标记`;bar.style.width=`${DATA.length?marked/DATA.length*100:0}%`}
const stTotal=document.getElementById('st-total'),stKnow=document.getElementById('st-know'),stFuzzy=document.getElementById('st-fuzzy'),stNo=document.getElementById('st-no'),bar=document.getElementById('bar');
function stateBtns(id){const s=states[id]||'';return `<div class="state"><button class="know ${s==='know'?'on':''}" onclick="mark(${id},'know',event)">熟练</button><button class="fuzzy ${s==='fuzzy'?'on':''}" onclick="mark(${id},'fuzzy',event)">模糊</button><button class="no ${s==='no'?'on':''}" onclick="mark(${id},'no',event)">不熟</button></div>`}
function mark(id,s,e){e?.stopPropagation();states[id]=s;save();updateStats();renderCurrent()}
function card(x,withState=true){return `<section class="card"><div class="meta">${x.sceneTitle} · ${String(x.id).padStart(2,'0')}</div><div class="en" onclick='speak(${JSON.stringify(x.en)})'>${x.en}</div><div class="zh">${x.zh}</div><div class="note">使用提示：${x.note}</div><div class="actions"><button class="speak" onclick='speak(${JSON.stringify(x.en)})'>🔊 美式发音</button></div>${withState?stateBtns(x.id):''}</section>`}
function renderTabs(){document.getElementById('scene-tabs').innerHTML=SCENES.map(s=>`<button class="${scene===s.id?'active':''}" onclick="scene='${s.id}';renderLearn()">${s.title}</button>`).join('')}
function renderLearn(){renderTabs();const arr=DATA.filter(x=>x.scene===scene);document.getElementById('learn-list').innerHTML=arr.map(x=>card(x)).join('')}
function setMode(m){mode=m;answerVisible=false;['learn','memorize','review','library'].forEach(v=>{document.getElementById(v+'-view').classList.toggle('hidden',v!==m);document.getElementById('nav-'+v).classList.toggle('active',v===m)});const copy={learn:['场景学习','按本次欧洲客户拜访流程学习。句子尽量短、自然、可直接在会议现场使用。'],memorize:['背诵模式','先只看英文，自己回忆中文意思和使用场景，再显示答案。'],review:['重点复习','集中复习你标记为“模糊”和“不熟”的句子。'],library:['完整句库','搜索英文、中文或场景，快速找到现场需要的表达。']};document.getElementById('hero-title').textContent=copy[m][0];document.getElementById('hero-desc').textContent=copy[m][1];renderCurrent()}
function memorizeArray(){let a=DATA;if(memFilter==='no')a=a.filter(x=>states[x.id]==='no');else if(memFilter==='fuzzy')a=a.filter(x=>states[x.id]==='fuzzy');else if(memFilter==='unseen')a=a.filter(x=>!states[x.id]);return a}
function memCard(x,i,total,tag){return `<section class="card"><div class="meta">${tag} · ${i+1} / ${total} · ${x.sceneTitle}</div><div class="en" onclick='speak(${JSON.stringify(x.en)})'>${x.en}</div><div class="actions"><button class="speak" onclick='speak(${JSON.stringify(x.en)})'>🔊 美式发音</button></div>${answerVisible?`<div class="zh">${x.zh}</div><div class="note">使用提示：${x.note}</div>${stateBtns(x.id)}`:`<div class="cover"><p>先自己回忆中文意思和适用场景。</p><button class="reveal" onclick="answerVisible=true;renderCurrent()">显示答案</button></div>`}</section>`}
function renderMem(){const a=memorizeArray();if(!a.length){document.getElementById('memorize-view').innerHTML='<div class="card empty">当前筛选没有句子。</div>';return}memIdx=Math.min(memIdx,a.length-1);document.getElementById('memorize-view').innerHTML=memCard(a[memIdx],memIdx,a.length,'背诵模式')+`<div class="nav"><button onclick="moveMem(-1)">← 上一句</button><button onclick="moveMem(1)">下一句 →</button></div><div class="actions" style="flex-wrap:wrap"><button class="speak" onclick="setMemFilter('all')">全部</button><button class="speak" onclick="setMemFilter('no')">只看不熟</button><button class="speak" onclick="setMemFilter('fuzzy')">只看模糊</button><button class="speak" onclick="setMemFilter('unseen')">只看未学习</button></div>`}
function setMemFilter(f){memFilter=f;memIdx=0;answerVisible=false;renderMem()}function moveMem(d){const a=memorizeArray();memIdx=Math.max(0,Math.min(a.length-1,memIdx+d));answerVisible=false;renderMem();scrollTo({top:0,behavior:'smooth'})}
function renderReview(){const a=DATA.filter(x=>states[x.id]==='no'||states[x.id]==='fuzzy');if(!a.length){document.getElementById('review-view').innerHTML='<div class="card empty">目前没有“模糊”或“不熟”的句子。先在场景学习或背诵模式中标记。</div>';return}reviewIdx=Math.min(reviewIdx,a.length-1);document.getElementById('review-view').innerHTML=memCard(a[reviewIdx],reviewIdx,a.length,'重点复习')+`<div class="nav"><button onclick="moveReview(-1)">← 上一句</button><button onclick="moveReview(1)">下一句 →</button></div>`}
function moveReview(d){const a=DATA.filter(x=>states[x.id]==='no'||states[x.id]==='fuzzy');reviewIdx=Math.max(0,Math.min(a.length-1,reviewIdx+d));answerVisible=false;renderReview();scrollTo({top:0,behavior:'smooth'})}
function renderLibrary(q=''){q=q.toLowerCase().trim();const a=DATA.filter(x=>!q||x.en.toLowerCase().includes(q)||x.zh.includes(q)||x.sceneTitle.includes(q));document.getElementById('library-view').innerHTML=`<section class="card"><input class="search" placeholder="搜索英文、中文或场景…" value="${q.replaceAll('"','&quot;')}" oninput="renderLibrary(this.value)"><div>${a.map(x=>`<div class="row" onclick="openSentence(${x.id})"><b>${x.en}</b><small>${x.sceneTitle} · ${x.zh} · ${label(states[x.id])}</small></div>`).join('')||'<div class="empty">没有找到匹配句子。</div>'}</div></section>`}
function openSentence(id){memFilter='all';memIdx=DATA.findIndex(x=>x.id===id);answerVisible=true;setMode('memorize')}
function renderCurrent(){if(mode==='learn')renderLearn();if(mode==='memorize')renderMem();if(mode==='review')renderReview();if(mode==='library')renderLibrary()}
updateStats();setMode('learn');
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
